project_name: aish
version: 2

builds:
  - id: aish
    main: .
    binary: ai
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

brews:
  - name: aish
    repository:
      owner: vklimontovich
      name: homebrew-aish
    commit_author:
      name: Vladimir Klimontovich
      email: vladimir@klimontovich.com
    homepage: https://github.com/vklimontovich/aish
    description: "AI-powered shell assistant"
    license: MIT
    install: |
      bin.install "ai"

release:
  github:
    owner: vklimontovich
    name: aish

changelog:
  use: git