version: 2
project_name: aish

builds:
  - id: aish
    main: .
    binary: aish
    goos: [ darwin, linux ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - -s -w

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: vklimontovich
    name: aish

changelog:
  use: git

snapshot:
  version_template: "{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}"