name: Update Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g., 0.5.7)"
        required: true
        type: string

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aish repo
        uses: actions/checkout@v4

      - name: Set up version
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ inputs.version }}"
            TAG="v$VERSION"
          else
            TAG=${GITHUB_REF#refs/tags/}
            VERSION=${TAG#v}
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Download release assets
        run: |
          mkdir dist
          platforms=("darwin_amd64" "darwin_arm64" "linux_amd64" "linux_arm64")
          for platform in "${platforms[@]}"; do
            FILE="aish_${{ steps.vars.outputs.version }}_${platform}.tar.gz"
            curl -L -o "dist/$FILE" "https://github.com/vklimontovich/aish/releases/download/${{ steps.vars.outputs.tag }}/$FILE"
          done

      - name: Calculate SHA256 checksums
        id: checksums
        run: |
          for FILE in dist/*; do
            BASENAME=$(basename "$FILE")
            SHA=$(shasum -a 256 "$FILE" | awk '{print $1}')
            echo "$BASENAME: $SHA"
            case $BASENAME in
              *darwin_amd64*) echo "sha_darwin_amd64=$SHA" >> $GITHUB_OUTPUT ;;
              *darwin_arm64*) echo "sha_darwin_arm64=$SHA" >> $GITHUB_OUTPUT ;;
              *linux_amd64*)  echo "sha_linux_amd64=$SHA" >> $GITHUB_OUTPUT ;;
              *linux_arm64*)  echo "sha_linux_arm64=$SHA" >> $GITHUB_OUTPUT ;;
            esac
          done

      - name: Clone homebrew-sh tap
        uses: actions/checkout@v4
        with:
          repository: vklimontovich/homebrew-aish
          token: ${{ secrets.CROSSREPO_GITHUB_TOKEN }}
          path: homebrew-sh

      - name: Generate versioned formula from template
        run: |
          VERSION="${{ steps.vars.outputs.version }}"
          TAG="${{ steps.vars.outputs.tag }}"
          FORMULA_NAME="aish@${VERSION}"
          FORMULA_PATH="homebrew-sh/Formula/$FORMULA_NAME.rb"
          VERSION_NO_DOTS="${VERSION//./}"
          
          sed -e "s/{{VERSION}}/$VERSION/g" \
              -e "s/{{TAG}}/$TAG/g" \
              -e "s/{{VERSION_NO_DOTS}}/$VERSION_NO_DOTS/g" \
              -e "s/{{SHA_DARWIN_AMD64}}/${{ steps.checksums.outputs.sha_darwin_amd64 }}/g" \
              -e "s/{{SHA_DARWIN_ARM64}}/${{ steps.checksums.outputs.sha_darwin_arm64 }}/g" \
              -e "s/{{SHA_LINUX_AMD64}}/${{ steps.checksums.outputs.sha_linux_amd64 }}/g" \
              -e "s/{{SHA_LINUX_ARM64}}/${{ steps.checksums.outputs.sha_linux_arm64 }}/g" \
              homebrew-sh/formula_template.rb > "$FORMULA_PATH"

      - name: Update latest formula symlink (aish.rb)
        run: |
          cp "homebrew-sh/Formula/aish@${{ steps.vars.outputs.version }}.rb" "homebrew-sh/Formula/aish.rb"

      - name: Commit and push formulas
        run: |
          cd homebrew-sh
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/aish@${{ steps.vars.outputs.version }}.rb Formula/aish.rb
          git commit -m "Add aish v${{ steps.vars.outputs.version }} formula"
          git push